apiVersion: v1
kind: Service
metadata:
  name: decision-engine-service
  namespace: fraud-detection
spec:
  type: ClusterIP
  selector:
    app: decision-engine
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
