apiVersion: v1
kind: Service
metadata:
  name: feature-enrichment-service
  namespace: fraud-detection
spec:
  type: ClusterIP
  selector:
    app: feature-enrichment
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
